# encoding: utf-8
Genre.delete_all

Genre.create([
                 {id: 1, name: "Chant"},
                 {id: 2, name: "Epos"},
                 {id: 3, name: "Folketone"},
                 {id: 4, name: "Hymne"},
                 {id: 5, name: "Irsk folketone"},
                 {id: 6, name: "Jul"},
                 {id: 7, name: "Kantate"},
                 {id: 8, name: "Koral"},
                 {id: 9, name: "Liturgi"},
                 {id: 10, name: "Madrigal"},
                 {id: 11, name: "Mag & Nunc"},
                 {id: 12, name: "Motett"},
                 {id: 13, name: "Nasjonalsang"},
                 {id: 14, name: "Oratorium"},
                 {id: 15, name: "Pop"},
                 {id: 16, name: "Preces & Responses"},
                 {id: 17, name: "Salme"},
                 {id: 18, name: "Spiritual"},
                 {id: 19, name: "Te Deum"},
                 {id: 20, name: "Verdslig"},
                 {id: 21, name: "Vise"},
                 {id: 22, name: "Kirkelig"},
                 {id: 23, name: "Anthem"},
                 {id: 24, name: "Samtid"}
             ])

Composer.delete_all

Composer.create([
                    {id: 1, name: "ABBA, arr. Ingegerd Idar"},
                    {id: 2, name: "Aafløy, Helge"},
                    {id: 3, name: "Aamodt, Thorleif"},
                    {id: 4, name: "Alfredson/Edenroth"},
                    {id: 5, name: "Allegri, Gregorio"},
                    {id: 6, name: "Alnes, Eyvind (1872-1932)"},
                    {id: 7, name: "Anderssen, Fridthjov"},
                    {id: 8, name: "Anon"},
                    {id: 9, name: "Atkins, I.A. / Bairstow, E.C. "},
                    {id: 10, name: "Aveyard, J."},
                    {id: 11, name: "Bach, Johann Sebastian (1685-1750)"},
                    {id: 12, name: "Bairstow, E.C."},
                    {id: 13, name: "Balfour Gardiner, H."},
                    {id: 14, name: "Barnard, John"},
                    {id: 15, name: "Battishill, Jonathan (1738-1801)"},
                    {id: 16, name: "Bayley, William / Atkins, Ivor Algernon"},
                    {id: 17, name: "Beck, Thomas"},
                    {id: 18, name: "Berger, Jean"},
                    {id: 19, name: "Bond, Anders"},
                    {id: 20, name: "Borg, Oscar"},
                    {id: 21, name: "Brahms, Johannes"},
                    {id: 22, name: "Briegel, Wolfgang Carl"},
                    {id: 23, name: "Britten, Benjamin (1913-1976)"},
                    {id: 24, name: "Bruch, Max (1838-1920)"},
                    {id: 25, name: "Bruckner, Anton (1824-1896)"},
                    {id: 26, name: "Buck, P.C."},
                    {id: 27, name: "Busengdal/Overøye"},
                    {id: 28, name: "Buverud, Olaf"},
                    {id: 29, name: "Byrd, William (1542-1623)"},
                    {id: 30, name: "Camidge, Matthew (1758-1844)"},
                    {id: 31, name: "Campian, Thomas"},
                    {id: 32, name: "Chipp, E.T."},
                    {id: 33, name: "Cook, Robert (1768-1814)"},
                    {id: 34, name: "Cooper, George"},
                    {id: 35, name: "Dahlen, Trond"},
                    {id: 36, name: "Darke, Harold"},
                    {id: 37, name: "Davies, Walford"},
                    {id: 39, name: "Dowland, John"},
                    {id: 40, name: "Draagen, Magne H."},
                    {id: 41, name: "Duruflé, Maurice"},
                    {id: 42, name: "Eccard, Johannes (1553-1611)"},
                    {id: 43, name: "Egge, Klaus"},
                    {id: 44, name: "Elgar, Edward"},
                    {id: 45, name: "Falck"},
                    {id: 46, name: "Fasmer Dahl/Sandvold"},
                    {id: 47, name: "Fauré, Gabriel"},
                    {id: 48, name: "Fleming, L. L."},
                    {id: 49, name: "Gardner, John"},
                    {id: 50, name: "Garrett, George M."},
                    {id: 51, name: "Gibbons, Orlando"},
                    {id: 52, name: "Goodson, Richard B. (1655-1718) / Hopkins, Edward John (1818-1901)"},
                    {id: 53, name: "Goss, John (1800-1880)"},
                    {id: 54, name: "Grieg, Edvard"},
                    {id: 55, name: "Gulliksen, Harald"},
                    {id: 56, name: "Gullin/Eriksson"},
                    {id: 57, name: "Hassler, Hans Leo"},
                    {id: 58, name: "Haweis/Webbe"},
                    {id: 59, name: "Hawes, William"},
                    {id: 60, name: "Haydn, Joseph"},
                    {id: 61, name: "Hindemith, Paul"},
                    {id: 62, name: "Homilius, G. A."},
                    {id: 63, name: "Hopkins, Edward John (1818-1901)"},
                    {id: 64, name: "Hovland, Egil"},
                    {id: 65, name: "Howells, Herbert (1892-1983)"},
                    {id: 66, name: "Hulkkonen, Jaakko"},
                    {id: 67, name: "Händel, Georg Friedrich"},
                    {id: 68, name: "Høybye, John"},
                    {id: 69, name: "Ihlebæk, G."},
                    {id: 70, name: "Jaques, Reginald"},
                    {id: 71, name: "Jennefelt, Thomas"},
                    {id: 72, name: "Karlsen, Kjell Mørk"},
                    {id: 73, name: "Kleive, Iver"},
                    {id: 74, name: "Klug, J."},
                    {id: 75, name: "Knight, Gerald Hocken (1908-1979)"},
                    {id: 76, name: "Kodály, Zoltán"},
                    {id: 77, name: "Kruse, Bjørn"},
                    {id: 78, name: "Kvandal, Johan"},
                    {id: 79, name: "Kverno, Trond"},
                    {id: 80, name: "Lasso, Orlando"},
                    {id: 81, name: "Leighton, Kenneth"},
                    {id: 82, name: "Ley, Henry George (1887-1962)"},
                    {id: 83, name: "Lloyd, C.H."},
                    {id: 84, name: "Lotti, Antonio"},
                    {id: 85, name: "Luboff, Norman"},
                    {id: 86, name: "Lundin, Bengt"},
                    {id: 87, name: "Macpherson, Charles / Rogers, J.L."},
                    {id: 88, name: "Martin, Gilbert M."},
                    {id: 89, name: "Mendelssohn, Felix Bartholdy (1809-1847)"},
                    {id: 90, name: "Millington, Andrew"},
                    {id: 91, name: "Monk, E. G."},
                    {id: 92, name: "Morley, Thomas"},
                    {id: 93, name: "Mozart, Wolfgang Amadeus (1756-1791)"},
                    {id: 94, name: "Møller, Svein"},
                    {id: 95, name: "Nielsen, Ludvig"},
                    {id: 96, name: "Noble"},
                    {id: 97, name: "Nordraak, Rikard"},
                    {id: 98, name: "Nystedt, Knut"},
                    {id: 99, name: "Næss, Carl-Andreas"},
                    {id: 100, name: "Olsson, Otto"},
                    {id: 101, name: "Ord, Boris"},
                    {id: 102, name: "Palestrina, Giovanni Pierluigi (1525-1594)"},
                    {id: 103, name: "Parry, Charles Hubert H."},
                    {id: 104, name: "Peterson-Berger, W."},
                    {id: 105, name: "Prätorius, Michael"},
                    {id: 106, name: "Purcell, Henry"},
                    {id: 107, name: "Pärt, Arvo (1935- )"},
                    {id: 108, name: "Ragnarsson, Hjálmar H."},
                    {id: 109, name: "Randall, John (1715-1799)"},
                    {id: 110, name: "Rathbone, George"},
                    {id: 111, name: "Rautavaara, Einojuhani"},
                    {id: 112, name: "Reading, John"},
                    {id: 113, name: "Reger, Max (1873-1916)"},
                    {id: 114, name: "Robinson, John (1682-1762)"},
                    {id: 115, name: "Rutter, John"},
                    {id: 116, name: "Saint-Saëns, Camille"},
                    {id: 117, name: "Sandvold, Arild"},
                    {id: 118, name: "Sark, Einar Trærup"},
                    {id: 119, name: "Sateren, Leland B."},
                    {id: 120, name: "Scarlatti, A (1660-1725)"},
                    {id: 121, name: "Schubert, Franz"},
                    {id: 122, name: "Schütz, Heinrich (1585-1672)"},
                    {id: 123, name: "Schütz/Kverno"},
                    {id: 124, name: "Shaw, Martin"},
                    {id: 125, name: "Sibelius, Jean"},
                    {id: 126, name: "Sigurbjörnsson, Thorkell"},
                    {id: 127, name: "Simonsen, Terje"},
                    {id: 128, name: "Sir Barnby, Joseph / Soaper, John"},
                    {id: 129, name: "Sir Davies, Henry Walford"},
                    {id: 130, name: "Skauen, Guttorm"},
                    {id: 131, name: "Skjølaas, Marius (1972-)"},
                    {id: 132, name: "Skotte, G"},
                    {id: 133, name: "Sløgedal, Bjarne"},
                    {id: 134, name: "Smith, William (1603-1645)"},
                    {id: 135, name: "Sommerro, Henning (1952-)"},
                    {id: 136, name: "South, Charles Frederic (1850-1916)"},
                    {id: 137, name: "Stanford, Charles Villiers (1852-1924)"},
                    {id: 138, name: "Stewart, Charles Hylton (1884-1932)"},
                    {id: 139, name: "Stonex, Henry"},
                    {id: 140, name: "Sumsion, Herbert W."},
                    {id: 141, name: "Takle, Mons Leidvin"},
                    {id: 142, name: "Tchaikovsky, Peter"},
                    {id: 143, name: "Templeton/Alldahl"},
                    {id: 144, name: "Thalben-Ball, George"},
                    {id: 145, name: "Thompson, Randall"},
                    {id: 146, name: "Thorarinsson, Jón"},
                    {id: 147, name: "Tomkins, Thomas (1572-1656)"},
                    {id: 148, name: "Trad"},
                    {id: 149, name: "Trad. Arr. Fleming"},
                    {id: 150, name: "Trad. Arr. Luboff"},
                    {id: 151, name: "Trad. Arr. Sløgedal"},
                    {id: 152, name: "Turle, James (1802-1882)"},
                    {id: 153, name: "Tveit, Sigvald"},
                    {id: 154, name: "Ukjent"},
                    {id: 155, name: "Verdi, Guiseppe"},
                    {id: 156, name: "Walmisley, Thomas Attwood (1814-1856)"},
                    {id: 157, name: "Walsh, Michael"},
                    {id: 158, name: "Wesley, Samual Sebastian (1810-1876)"},
                    {id: 159, name: "Weyse, C. E. F."},
                    {id: 160, name: "Widéen, Ivar"},
                    {id: 161, name: "Willcocks, David"},
                    {id: 162, name: "Zöllner, C."},
                    {id: 163, name: "Årva, Øystein"},
                    {id: 164, name: "Öhrwall, Anders"},
                    {id: 165, name: "Ødegård, Henrik"},
                    {id: 168, name: "Diverse"},
                    {id: 169, name: "Vaughan Williams, Ralph (1872-1958)"},
                    {id: 170, name: "Cornelius, Peter"},
                    {id: 171, name: "Victoria, Tomas Luis de (1548-1611)"}
                ])

Period.delete_all

Period.create([
                  {id: 1, name: "Barokk"},
                  {id: 2, name: "Klassisisme"},
                  {id: 3, name: "Nasjonalromantikk"},
                  {id: 4, name: "Nyere"},
                  {id: 5, name: "Renessanse"},
                  {id: 6, name: "Romantikken"},
                  {id: 7, name: "Trad."}
              ])